/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Achievement = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
});
export const Activity = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Achievement = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
  });
  const Activity = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };